"""globally unique dt project

Revision ID: 37611c66854e
Revises: b9106eeb44ed
Create Date: 2026-07-23 08:06:08.854506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37611c66854e'
down_revision: Union[str, Sequence[str], None] = 'b9106eeb44ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dependency_track_projects_ef_project_id_name_key'), 'dependency_track_projects', type_='unique')
    op.drop_constraint(op.f('dependency_track_projects_name_parent_uuid_key'), 'dependency_track_projects', type_='unique')
    op.create_unique_constraint(op.f('dependency_track_projects_name_key'), 'dependency_track_projects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dependency_track_projects_name_key'), 'dependency_track_projects', type_='unique')
    op.create_unique_constraint(op.f('dependency_track_projects_name_parent_uuid_key'), 'dependency_track_projects', ['name', 'parent_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('dependency_track_projects_ef_project_id_name_key'), 'dependency_track_projects', ['ef_project_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
