"""Init db

Revision ID: 844bb24a18ad
Revises: 
Create Date: 2026-06-24 12:12:23.048833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844bb24a18ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eclipse_foundation_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_track_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ef_project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ef_project_id'], ['eclipse_foundation_projects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_uuid')
    )
    op.create_table('workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ef_project_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ef_project_id'], ['eclipse_foundation_projects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('repo_owner', sa.String(), nullable=False),
    sa.Column('repo_owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', 'repo_owner', 'repo_owner_id')
    )
    op.create_table('jenkins_workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jenkins_workloads')
    op.drop_table('github_workloads')
    op.drop_table('workloads')
    op.drop_table('dependency_track_projects')
    op.drop_table('eclipse_foundation_projects')
    # ### end Alembic commands ###
