"""unique dt project per ef_project_id and name

Revision ID: b9106eeb44ed
Revises: 844bb24a18ad
Create Date: 2026-07-17 08:50:54.737637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9106eeb44ed'
down_revision: Union[str, Sequence[str], None] = '844bb24a18ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSTRAINT_NAME = 'dependency_track_projects_ef_project_id_name_key'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(CONSTRAINT_NAME, 'dependency_track_projects', ['ef_project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(CONSTRAINT_NAME, 'dependency_track_projects', type_='unique')
    # ### end Alembic commands ###
